name: 'Action 1'
description: 'A sample GitHub Action for demonstration'
inputs:
  example-input:
    description: 'An example input'
    required: true
    default: 'default-value'
runs:
  using: 'node16'
  main: 'src/index.js'

